# Receiver is the component that receives telemetry data from the emitter.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"


processors:
  batch: 

# Exporter is the component that exports telemetry data to a backend.
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlphttp:
      endpoint: http://tempo:4418
      tls:
        insecure: true
  debug:
    verbosity: detailed
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

# Service is the component that defines the pipeline of telemetry data. This is required to connect the receivers, processors, and exporters.
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/logs]