# Receiver is the component that receives telemetry data from the emitter.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
# Exporter is the component that exports telemetry data to a backend.
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
      endpoint: tempo:4317
      tls:
        insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

# Service is the component that defines the pipeline of telemetry data. This is required to connect the receivers, processors, and exporters.
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]