services:
  flask-app:
    build: .
    container_name: flask-app
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - '4317:4317'
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
  promtheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}