# Receiver is the component that receives telemetry data from the emitter.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5000
# Processor is the component that processes the telemetry data.
processors:
# Exporter is the component that exports telemetry data to a backend.
exporters:
  prometheus:
    endpoint: 0.0.0.0:9090
# Service is the component that defines the pipeline of telemetry data. This is required to connect the receivers, processors, and exporters.
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]